#include<iostream>
#include<string>
#include<cstring>
#include<algorithm>
#include<cstdlib>
#include<cstdio>
using namespace std;
char* str="GAGGATGGGTGGATGTGGGGTTAGGTGACTGTGGAGGCGGGGCTGGTCTCTGTCCAGGTGACAGGTGGATGGTGGAGCTGGAGGAGCCACTCGGAGCCTCCAAGGCTGGGGAGGGTGGAGGGGGGAGGCAGGTCGGTGTCCCAGGCCACACCTGTTGACTAAGGGATTAGGATGTTGTGTCCCTGCCAGCCCTCCTCCAATAAGCCCCTCTGGGCCTGCAGGGAGAGGAGGAGCCTTGCCATGTAAACTGTATTTTTAGTTCCCTGTGCCTCTCCCCGGCTGCTATAAGACACCTCTCCCCACCCCCAGCCCTGGCCGCTTGGCTGGAGGCTCTGCGAGGACAGCTGGGGAGAAGGGGAGCTGTGGTCAGTATGATGGATGCTGAGGGGCTGGAGAGGAGCAGCCCTGGTGGGTGGGTTCCTGGGAGTCTGGAGCAAGCTTGGGGGTTCTGCTGCCCCATCAAGGGCCTTGAGCAGGTCCTGCAACTCCCAGGCCTCAGCCCTGCTCTGAGC";
int main(int argc, char* argv[])
{
	int n, m, l;
	// cin >> n >> m >> l;
	n = atoi(argv[1]);
	m = atoi(argv[2]);
	l = atoi(argv[3]);
	cout << n << " " << m << " " << l << endl;
	for(int i = 0; i < n; i++)
	{
		cout << str[i];
	}
	cout<<endl;
}
